# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

mydb = mysql.connector.connect(
    host = "localhost",
    user = "Ramen",
    password = "Ramen"
)

windows = [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
windowCoords = [
    0,
    QtCore.QRect(370, 400, 16, 16),
    QtCore.QRect(540, 200, 16, 16)
]

cursor = mydb.cursor()
cursor.execute("SELECT * FROM ramen.ramen")

for x in cursor:
    windows[x[0]] = x[1]

class Ui_MainWindow(object):

    def checkWindows(self, window, coords, windowName, _translate):
        if(window == 1):
            windowName.setText("open")
        else:
            windowName.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/img/greenDot.png\"/></p></body></html>"))
        windowName.setGeometry(coords)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.blueprint = QtWidgets.QLabel(self.centralwidget)
        self.blueprint.setGeometry(QtCore.QRect(0, 0, 501, 411))
        self.blueprint.setObjectName("blueprint")
        self.window1 = QtWidgets.QLabel(self.centralwidget)
        # self.window1.setGeometry(QtCore.QRect(370, 400, 16, 16))
        self.window1.setObjectName("window1")
        self.window2 = QtWidgets.QLabel(self.centralwidget)
        # self.window2.setGeometry(QtCore.QRect(540, 200, 16, 16))
        self.window2.setObjectName("window2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blueprint.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/img/Building.png\" width=\"500\" /></p></body></html>"))
        # self.window1.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/img/greenDot.png\"/></p></body></html>"))
        # self.window2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/img/greenDot.png\"/></p></body></html>"))

        self.checkWindows(windows[1], windowCoords[1], self.window1, _translate)
        self.checkWindows(windows[2], windowCoords[2], self.window2, _translate)

import app_qrc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showFullScreen()
    MainWindow.show()
    sys.exit(app.exec_())
